DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS PRICES;

CREATE TABLE GROUPS (
  BRAND_ID INT NOT NULL PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PRICES (
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    PRIMARY KEY(BRAND_ID, PRODUCT_ID, START_DATE, END_DATE),
    FOREIGN KEY (BRAND_ID) REFERENCES GROUPS (BRAND_ID)
);